export const SOCKET_EVENTS = {
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    FETCH_STORE: 'FETCH_STORE',
    SUBMIT_MESSAGE: 'SUBMIT_MESSAGE',
    PUSH_CONVERSATION: 'PUSH_CONVERSATION',
    PUSH_STORE: 'PUSH_STORE',
};
